{% set name = "linmarg" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/linmarg-{{ version }}.tar.gz
  sha256: 4c593582c166805e548f50ad36ad17f70096672b7f18e3546d0b3a85ab1dcfb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy

test:
  imports:
    - linmarg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.unige.ch/delisle/linmarg
  summary: Linear parameters marginalizer
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbdelisle
